# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa693dd831139b6ce24401a082b1c5415f7d1ecb0cdb6c4bcd768830ff73e2517adb9e947ea574826e8031204fc954478da699870bc3d2b0b80736052b22e7d2

test:
  secret_key_base: 0bef7b349cf36f2e82e163304f5b9bda38841d48fd7db6b04916a9d214e111b4d5a898fa7d02cdf1a7916c0e9aec566dfb6afc795e653edb4f1855ff75f37d49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
